# .github/workflows/generate-reports.yml
name: Generate Supabase Reports

on:
  schedule:
    # 00:30 Europe/Berlin = 22:30 UTC (am Vortag)
    - cron: '12 1 * * *'
  workflow_dispatch:

env:
  TZ: Europe/Berlin

jobs:
  reports:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # Passe nach Anzahl deiner Kunden / CHUNK_SIZE an
        chunk_index: [0, 1, 2, 3, 4]
      max-parallel: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run generate-reports.js (Chunk ${{ matrix.chunk_index }})
        run: |
          echo "🎯 Processing chunk $CHUNK_INDEX (size $CHUNK_SIZE)"
          node generate-reports.js
        env:
          SUPABASE_URL:             ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          CHUNK_INDEX:              ${{ matrix.chunk_index }}
          CHUNK_SIZE:               5
          SENDGRID_API_KEY:        ${{ secrets.SENDGRID_API_KEY }}
          SENDGRID_SENDER:        ${{ secrets.SENDGRID_SENDER }}
