name: Generate Manual Reports

on:
  workflow_dispatch:
    inputs:
      schema:
        description: 'Kundenschema (firma_slug)'
        required: true
      workers:
        description: 'Kommaseparierte UUIDs der Arbeiter'
        required: true
      start_date:
        description: 'Startdatum (YYYY-MM-DD)'
        required: true
      end_date:
        description: 'Enddatum (YYYY-MM-DD)'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Deps
        run: npm ci

      - name: Generate Manual Reports
        run: |
          node generate-manual-report.js \
            "${{ github.event.inputs.schema }}" \
            "${{ github.event.inputs.workers }}" \
            "${{ github.event.inputs.start_date }}" \
            "${{ github.event.inputs.end_date }}"
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
